### ISSUE TITLE
Fix hanging commits on dot etcd-backup-dot-cronjob

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#380] opened 2018-04-12 14:21 UTC
The following command hangs, and this is the reason why the cron jobs are also hanging on the etcd-backups.
```
dm switch etcd-backup-dot-cronjob
dm commit -m "blah"
```

dm logs seem to be spinning on trying to procure the filesystem for the dot 
```
"[timestamp=2018-04-12T11:13:14Z] [instance_id=8764352245442910897] [pod_id=dotmesh-lzz7j] Error procuring filesystem: timed out trying to procure 47fef5a4-7788-45c7-7953-171f35e8ab2e, please try again, pausing and trying again...\n"
"[timestamp=2018-04-12T11:13:14Z] [instance_id=8764352245442910897] [pod_id=dotmesh-lzz7j] 2018/04/12 11:13:14 Attempting to move 47fef5a4-7788-45c7-7953-171f35e8ab2e from 806ed3b7173f9693 to me (2a1f51b88403779)\n"
"[timestamp=2018-04-12T11:13:14Z] [instance_id=8764352245442910897] [pod_id=dotmesh-lzz7j] 2018/04/12 11:13:14 globalFsRequest: setting '/dotmesh.io/filesystems/requests/47fef5a4-7788-45c7-7953-171f35e8ab2e/0c9b8eda-469f-4761-7044-fe72ceb35bc6' to '{\"Name\":\"move\",\"Args\":{\"target\":\"2a1f51b88403779\"}}'\n"
"[timestamp=2018-04-12T11:13:14Z] [instance_id=8764352245442910897] [pod_id=dotmesh-lzz7j] 2018/04/12 11:13:14 globalFsRequest 47fef5a4-7788-45c7-7953-171f35e8ab2e <Event move: target: 2a1f51b88403779>\n"
"[timestamp=2018-04-12T11:13:13Z] [instance_id=4557252902214069511] [pod_id=dotmesh-vkg6x] Error procuring filesystem: timed out trying to procure 47fef5a4-7788-45c7-7953-171f35e8ab2e, please try again, pausing and trying again...\n"
"[timestamp=2018-04-12T11:13:13Z] [instance_id=4557252902214069511] [pod_id=dotmesh-vkg6x] 2018/04/12 11:13:13 Attempting to move 47fef5a4-7788-45c7-7953-171f35e8ab2e from 806ed3b7173f9693 to me (198cdf7c12622838)\n"
"[timestamp=2018-04-12T11:13:13Z] [instance_id=4557252902214069511] [pod_id=dotmesh-vkg6x] 2018/04/12 11:13:13 globalFsRequest: setting '/dotmesh.io/filesystems/requests/47fef5a4-7788-45c7-7953-171f35e8ab2e/b8f682a5-bd45-41e9-4e6c-0b2c8e043cb1' to '{\"Name\":\"move\",\"Args\":{\"target\":\"198cdf7c12622838\"}}'\n"
"[timestamp=2018-04-12T11:13:13Z] [instance_id=4557252902214069511] [pod_id=dotmesh-vkg6x] 2018/04/12 11:13:13 globalFsRequest 47fef5a4-7788-45c7-7953-171f35e8ab2e <Event move: target: 198cdf7c12622838>\n"
```

**Comment by lukemarsden** [comment] 2018-04-16 09:10
possibly caused by https://github.com/dotmesh-io/ops/issues/55, if it's not happening right now then we've lost it, closing for now.

**Closed by lukemarsden** 2018-04-16 09:10 UTC
Labels: bug
