### ISSUE TITLE
dm list needs to be read-after-write consistent across a cluster

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#411] opened 2018-05-10 07:16 UTC
in order to reliably script against a multi-node dotmesh cluster (like smoke.sh attempts to do) we need read-after-write consistency, in particular:

* `dm push` to one node
* `dm list` on another node

needs to show the result of the push immediately after the push completes.

currently, for historical reasons, `dm list` enumerates the fsMachines _on the node where the request lands_. while this sort-of works, it's eventually consistent because it depends on fsMachines being created and started on all nodes in order to show up in the enumeration. it would be better for `dm list` to go directly to etcd and read from the registry, this way it will always return fresh information.

it should be possible to make it a lot faster while we're at it, fixing https://github.com/dotmesh-io/dotmesh/issues/337.

**Comment by lukemarsden** [comment] 2018-05-10 07:25
we could start by consulting the local cache of the registry, and only if that doesn't improve the smoke tests go to etcd on every `list`.

**Comment by alaric-datamesh** [comment] 2018-05-11 09:05
Perhaps it doesn't.

`dm list` calls `DotmeshRPC.List`, which is a near-duplicate of `DotmeshRPC.AllDotsAndBranches`, although the latter operates through a slightly different mechanism; both are based on the caches we get from etcd rather than fsmachines, so should be pretty up-to-date.

However, using `dm list` to test for existence of a dot on a random node is, perhaps, an anti-pattern - `dm list` does a whole lot more work than is necessary for that. Better to run `dm dot show DOTNAME`, which returns a shell status code of success (dot exists) or failure (dot doesn't exist or something else went wrong), and retry a bit to overcome latency in etcd updates. `dm list` can be improved in many ways, but this use case is best handled in other ways,

**Closed by alaric-datamesh** 2018-05-11 09:05 UTC
Labels: bug
