### ISSUE TITLE
Bazel seems incompatible with how we version things

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#523] opened 2018-07-28 07:26 UTC
Principle of bazel seems to be that the binaries are only a function of the source code. But ours aren't - the dm binary also encodes in it the version of the server as a function of the git environment. Under bazel, if the dm binary isn't recompiled because the code hasn't changed, that can block changes to the server code being released (or even tested?) because the version of the server installed by, say `dm cluster init` depends on the version (docker image tag) baked into the `dm` client.

Either:
- figure out how to tell bazel that there's an additional build input of the version (this will presumably make the caching less effective)
- stop using bazel and go back to simple containerised builds with go caching
- change how the client determines which version of the server to install somehow

**Comment by alaric-dotmesh** [comment] 2018-07-30 08:09
"Making the caching correct" isn't "Making the caching less effective" at all :-)

The version changes come in via `version_status.sh` - I'd have thought that Bazel was aware that changes to the output of this script should cause a rebuild of everything that refers to variables extract from it. So perhaps the problem is in how it knows what depends on what.

`cmd/dm/BUILD.bazel` says:

```python
go_library(
    name = "go_default_library",
    srcs = ["dotmesh.go"],
    importpath = "github.com/dotmesh-io/dotmesh/cmd/dm",
    visibility = ["//visibility:private"],
    deps = [
        "//cmd/dm/pkg/commands:go_default_library",
        "//vendor/github.com/opentracing/opentracing-go:go_default_library",
        "//vendor/github.com/openzipkin/zipkin-go-opentracing:go_default_library",
    ],
)

go_binary(
    name = "dm",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
    x_defs = {"main.clientVersion": "{VERSION}",
    "main.dockerTag": "{DOCKERTAG}"},
    static = "on"
)
```

I'd expect it, when `DOCKERTAG` changes in the output of `version_status.sh`, to not *rebuild* the client (as it's built into a library), but to *relink* it as the `x_defs` inputs to the `go_binary` declaration have changed.

Is this a bug in `x_defs`, not being correctly declared as a meaningful input to the build process? I found [the implementation](https://github.com/bazelbuild/rules_go/pull/27/commits/5f48b05951a6f20c9152b11bcbfdeb00b0456d17#diff-4f5b14321ffa5e059d98fdcd4190f632) but I don't know how detecting changes in the build process is meant to work in Bazel, so who knows?

**Comment by alaric-dotmesh** [comment] 2018-07-30 08:14
This seems like a duplicate of https://github.com/dotmesh-io/ops/issues/85 - moving to there as @Godley's working on a fix

**Closed by alaric-dotmesh** 2018-07-30 08:14 UTC
