### ISSUE TITLE
deletion flakes

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#553] opened 2018-08-17 15:41 UTC
### User requirement
As a dotmesh user, I want deletion to always work so that I can delete things.

```
luke@mind:~/ps/dotscience-agent$ dm dot show lukemarsden/words-reversed
Dot lukemarsden/words-reversed:
Response '{"jsonrpc":"2.0","error":{"code":-32000,"message":"No known filesystem with id ","data":null},"id":6334824724549167320}
' yields error No known filesystem with id
luke@mind:~/ps/dotscience-agent$ dm dot delete lukemarsden/words-reversed
Please confirm that you really want to delete the dot lukemarsden/words-reversed, including all branches and commits? (enter Y to continue): Y
Response '{"jsonrpc":"2.0","error":{"code":-32000,"message":"105: Key already exists (/dotmesh.io/filesystems/deleted/e918a0e9-a2db-4526-79a3-97b40b7d15d8) [449578984]","data":null},"id":4037200794235010051}
' yields error 105: Key already exists (/dotmesh.io/filesystems/deleted/e918a0e9-a2db-4526-79a3-97b40b7d15d8) [449578984]
luke@mind:~/ps/dotscience-agent$ dm dot show lukemarsden/words-reversed
Dot lukemarsden/words-reversed:
Response '{"jsonrpc":"2.0","error":{"code":-32000,"message":"No known filesystem with id ","data":null},"id":6334824724549167320}
' yields error No known filesystem with id
luke@mind:~/ps/dotscience-agent$ dm list
Current remote: dotscience-test-remote-1709f301-hub (use 'dm remote -v' to list and 'dm remote switch' to switch)

  DOT                                      BRANCH  SERVER            CONTAINERS  SIZE       COMMITS  DIRTY
  binocarlos/dotmesh-stack-dumps           master  198cdf7c12622838              -          1        -
  lukemarsden/agent1                       master  198cdf7c12622838              -          1        -
  lukemarsden/agent2                       master  2a1f51b88403779               -          1        -
  lukemarsden/combined-houses              master  806ed3b7173f9693              -          1        -
  lukemarsden/dotscience-output            master  198cdf7c12622838              -          7        -
  lukemarsden/dotscience-project           master  2a1f51b88403779               -          8        -
  lukemarsden/dotscience-project-houses    master  806ed3b7173f9693              -          1        -
  lukemarsden/jenkins-initial              master  806ed3b7173f9693              -          1        -
  lukemarsden/jenkins-with-meme-generator  master  198cdf7c12622838              -          1        -
  lukemarsden/michael-dotscience-project   master  806ed3b7173f9693              -          3        -
  lukemarsden/michael-model                master  2a1f51b88403779               -          2        -
  lukemarsden/moby_counter                 master  806ed3b7173f9693              -          1        -
  lukemarsden/mobycounter_app              master  2a1f51b88403779               -          1        -
  lukemarsden/model                        master  198cdf7c12622838              -          1        -
  lukemarsden/myapp                        master  806ed3b7173f9693              -          2        -
  lukemarsden/samba                        master  198cdf7c12622838              -          1        -
  lukemarsden/test                         master  2a1f51b88403779               19.50 kiB  1        -
  lukemarsden/test_again                   master  198cdf7c12622838              -          1        -
  lukemarsden/words                        master  198cdf7c12622838              20.50 kiB  1        -
  lukemarsden/words-reversed               master  198cdf7c12622838              -          2        -
  lukemarsden/workspace                    master  806ed3b7173f9693              25.00 kiB  1        -```
```

### Key acceptance criteria
- [ ] Deletion should not be flaky.

**Comment by rusenask** [comment] 2018-12-17 12:34
duplicate of https://github.com/dotmesh-io/dotmesh/issues/488

**Closed by rusenask** 2018-12-17 12:34 UTC
Labels: bug
